### ISSUE TITLE
Investigate why the check-onnx-backend-numerical-nnpa tests fail with multithreading

### ISSUE THREAD

**Issue by hamptonm1** [onnx/onnx-mlir#2666]
We are using pytest-xdist to run our tests in parallel. When we use about 4 threads to speed up the process of testing, it appears with zAIU that the tests are being randomly spawned and that there is a race condition. Before the tests found in NNPA/numerical finishes, there are about 7 targets from NNPA/backend which begin to run and causes a conflict. So the temp work-around is to lessen the threads when running the NNPA tests.

With that being said, let's figure out a proper solution to run check-onnx-backend-numerical-nnpa with more threads successfully.

**Comment by hamptonm1** [comment]
FYI- @tungld @AlexandreEichenberger

**Comment by tungld** [comment]
@gongsu832 any thoughts on how to debug and fix this issue? Thanks!

**Comment by gongsu832** [comment]
It's hard to tell without seeing any error output.

**Comment by hamptonm1** [comment]
When running the target `check-onnx-backend-numerical-nnpa` we get a segmentation fault error as shown below but when changing the amount of threads to NPROC=1 we do not have that problem like here https://github.com/onnx/onnx-mlir/blob/ba3758453855db3998332c804703128ef29af2b3/test/accelerators/NNPA/backend/CMakeLists.txt#L77:

```
bringing up nodes...
bringing up nodes...
Fatal Python error: Segmentation fault
Thread 0x000003ffa06ff840 (most recent call first):
  File “/usr/lib/python3/dist-packages/execnet/gateway_base.py”, line 400 in read
  File “/usr/lib/python3/dist-packages/execnet/gateway_base.py”, line 432 in from_io
  File “/usr/lib/python3/dist-packages/execnet/gateway_base.py”, line 967 in _thread_receiver
  File “/usr/lib/python3/dist-packages/execnet/gateway_base.py”, line 220 in run
  File “/usr/lib/python3/dist-packages/execnet/gateway_base.py”, line 285 in _perform_spawn
```

```
Extension modules: google.protobuf.pyext._message, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg.lapack_lite, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator (total: 15)


[2:25](https://ibm-systems-z.slack.com/archives/D471HFRGB/p1701890709082029)
 File "/usr/lib/python3/dist-packages/xdist/remote.py", line 91 in pytest_runtestloop
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 323 in _main
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 269 in wrap_session
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3/dist-packages/xdist/remote.py", line 291 in <module>
  File "/usr/lib/python3/dist-packages/execnet/gateway_base.py", line 1084 in executetask
  File "/usr/lib/python3/dist-packages/execnet/gateway_base.py", line 220 in run
  File "/usr/lib/python3/dist-packages/execnet/gateway_base.py", line 285 in _perform_spawn
  File "/usr/lib/python3/dist-packages/execnet/gateway_base.py", line 267 in integrate_as_primary_thread
  File "/usr/lib/python3/dist-packages/execnet/gateway_base.py", line 1060 in serve
  File "/usr/lib/python3/dist-packages/execnet/gateway_base.py", line 1554 in serve
  File "<string>", line 8 in <module>
  File "<string>", line 1 in <module>

Extension modules: google.protobuf.pyext._message, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg.lapack_lite, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtran
```

**Comment by hamptonm1** [comment]
However, we run each test in the target `check-onnx-backend-numerical-nnpa ` one by one all tests do pass. I think the tests are not completing in said target and stepping on each other's toes so to speak. So like while one test is still running another one is being spawned off and we get this segmentation fault error. This is just my theory but not sure how to increase the threads to bypass this issue.

**Comment by gongsu832** [comment]
NNPA tests segfault because different set of tests such as check-onnx-backend-nnpa, check-onnx-backend-dynamic-nnpa, check-onnx-backend-constant-nnpa, etc. are running in parallel and generating model.so in the same directory.

https://github.com/onnx/onnx-mlir/pull/2671 should fix the problem.

**Comment by hamptonm1** [comment]
> NNPA tests segfault because different set of tests such as check-onnx-backend-nnpa, check-onnx-backend-dynamic-nnpa, check-onnx-backend-constant-nnpa, etc. are running in parallel and generating model.so in the same directory.
> 
> #2671 should fix the problem.

Actually that was my assumption prior to me opening this issue... I tried separating each target into their own folder similar to what we do for the backend targets like here:  file:https://github.com/onnx/onnx-mlir/blob/main/test/backend/CMakeLists.txt#L145 

@tungld can attest to this but I already tried that in our internal repo and tested via the proper hardware and that still did not resolve our issue. I can spin up another container and execute the same commands and show you the results if you like. 

I think it doesn't hurt to merge that PR in anyways, to make the CMakeList.txt files consistent in terms of formatting.

**Comment by tungld** [comment]
> I can spin up another container and execute the same commands and show you the results if you like.

How about merging the PR so that we can have an image with that and see if it solves the issue?

**Comment by gongsu832** [comment]
NNPA tests set `TEST_CASE_BY_USER` which ignores `ONNX_HOME`. PR https://github.com/onnx/onnx-mlir/pull/2671 has been updated and should really fix the segfault problem.

**Comment by tungld** [comment]
> NNPA tests set TEST_CASE_BY_USER which ignores ONNX_HOME. PR https://github.com/onnx/onnx-mlir/pull/2671 has been updated and should really fix the segfault problem.

Excellent! That would be the root cause. Thanks so much @gongsu832!

**Comment by hamptonm1** [comment]
Sounds good... I will confirm if this actually solves the problem via testing since we do not execute this target in our builds and no one has really tested the `NNPA` targets. Thanks for the PR.

**Comment by hamptonm1** [comment]
> > I can spin up another container and execute the same commands and show you the results if you like.
> 
> How about merging the PR so that we can have an image with that and see if it solves the issue?

I already confirmed the original PR would not solve the issue... I already tried that myself but I can try now with the update for the same PR with the change to TEST_CASE_BY_USER to see if that solves it.

**Comment by hamptonm1** [comment]
Okay the update for TEST_CASE_BY_USER is what solved it. I just tested.... closing this issue out now. Thanks
